version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ticketplus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticketplus
      MYSQL_USER: ticketuser
      MYSQL_PASSWORD: ticketpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data:
